name: Crowdin Action

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.19
      with:
        upload_translations: true
        download_translations: true
        pull_request_labels: "translations"
        skip_untranslated_strings: false
        skip_untranslated_files: false
        commit_message: "New Crowdin translations by Github Action"
        pull_request_title: "New Crowdin translations to review and merge"
#         project_id: 441714
#         token: b56afc7b4872a971c819ae49f409bba5fe79603b4b0dadc0178ff795e59bbdf93c48dc8602fbce1c
#       env:
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
