name: Crowdin Action

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.19
      with:
        upload_translations: true
        download_translations: true
        pull_request_labels: 'translations'
        skip_untranslated_strings: false
        skip_untranslated_files: false
        commit_message: 'New Crowdin translations by Github Action'
        pull_request_title: 'New Crowdin translations to review and merge'
        project_id: 441714
        token: 8aeab7e4060222ec22dd074a8fa6a29dc034c4870be4dc3cd38de39ebcd291f9aa5926fb9651fec6
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
